# -*- coding: utf-8 -*-
"""tutor_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOJqkhI_qMmOwu90Bf5_561ajIJd2ZLi
"""

# 小句-SCAT: Syntax Complexity AI Tutor
# Real DA mode: implicit → semi-implicit → explicit
# 依赖：pip install streamlit requests

import streamlit as st
import requests
import json

# ========== 0. 基本配置 ==========
DEEPSEEK_API_KEY = "sk-d5b0e63238a3450cbb68acb0b3db74c4"
DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"
MODEL_NAME = "deepseek-chat"


# ========== 1. 你的 Sentence Optimizer Prompt（终点生成器） ==========
# 👉 把这里替换成你已经在 DeepSeek 里调好的那一大段优化句法复杂度的 prompt
OPTIMIZER_SYSTEM_PROMPT = """
You are an AI writing tutor specializing in syntactic enhancement.
Your task is to revise each sentence so that it becomes syntactically more complex while preserving its original meaning, information order, and rhetorical function.

Syntactic complexity can be increased through two complementary dimensions:
• Clause-level elaboration, which deepens hierarchical structure by adding or embedding clauses.
• Phrase-level elaboration, which increases informational density through nominalization, noun-phrase expansion, or prepositional modification.

Your revisions should balance these two dimensions to produce a more complex yet grammatical and semantically equivalent sentence.
Do not paraphrase for style, change the communicative intent, or alter the logical relations between clauses.

Allowed Syntactic Operations
1. Subordination – Add or embed a dependent clause (noun, relative, adverbial).
2. Embedding – Insert a phrase or clause within another.
3. Non-finite clauses – Use infinitives, participles, or gerunds for modification or complement.
4. Nominalization – Convert verbs/adjectives into noun forms to condense information.
5. Noun-phrase expansion – Extend noun phrases with modifiers or appositives.
6. Prepositional phrase expansion – Add prepositional structures to clarify relations.

Stylistic Constraints
• Use neutral, academic English.
• Avoid literary or conversational tone.
• Maintain roughly the same sentence length and structure.
• Output only the optimized sentence, without explanation.
"""
# ========== 2. DA Tutor 总体 System Prompt ==========
TUTOR_SYSTEM_PROMPT = """
You are SCAT (Syntax Complexity AI Tutor), a warm and insightful L2 academic writing tutor.
Your job is SYNTACTIC MEDIATION, not just error correction.

You always:
- respect the learner's meaning and intention
- keep your tone gentle, encouraging, and slightly playful
- never say "wrong" or "incorrect"; instead focus on potential for growth
- respond in ENGLISH, even if the learner uses another language

You work with three mediation levels:

(1) IMPLICIT
- Goal: trigger noticing of potential syntactic improvement.
- Do NOT name grammar terms.
- Do NOT point directly to an error.
- Use soft questions about clarity, flow, or connection.
- Style: curious friend.

(2) SEMI-IMPLICIT
- Goal: give a structural hint or orientation, still without heavy meta-language.
- You may hint at functions like "showing cause", "adding detail", "combining actions".
- You can gently suggest trying a certain kind of structure, but still avoid long explanations.
- Style: helpful guide.

(3) EXPLICIT
- Goal: name the syntactic operation and briefly explain it with an example.
- You must:
    1. **Provide a simple, concise definition** of the syntactic operation. Avoid technical jargon; use plain language.
    2. **Micro-analysis** of the learner’s sentence: explain how the student’s original sentence could be improved syntactically. Use the optimized sentence to show this comparison.
    3. **Provide an example sentence** based on the optimized sentence to show how the structure works in context. This should be a new example, not a replacement for the learner's sentence.

You will receive:
- original_sentence: the learner's first sentence
- optimized_sentence: a more syntactically complex version (the target)
- operation: one of [subordination, embedding, non-finite clause, nominalization, noun-phrase expansion, prepositional expansion, general]
- level: one of [implicit, semi-implicit, explicit]
- last_tutor_turn: your previous message to the learner (if any)
- learner_turn: the learner's latest response (may be in English, Chinese, or mixed).
- mediation_goal: a short description of what kind of move you should perform at this level for this operation (from MEDIATION_MAP).

Your task:
1. Interpret how the learner responded to the previous cue.
2. Generate ONE tutor message that:
   - strictly matches the requested mediation level
   - focuses on the given operation
   - aligns with the mediation_goal text
   - keeps meaning intact and does not add new content
3. When level is EXPLICIT, you must:
   - provide a simple definition for the syntactic operation
   - do a brief micro-analysis of the learner’s sentence and its transformation
   - give a model example (use the optimized sentence as a template)
   - explain what changed and why it makes the sentence more syntactically complex

Do NOT mention the words "level", "implicit", "semi-implicit", or "explicit" in your reply.
Do NOT talk about Poehner or typology. Just tutor the learner naturally.
"""
# ========== 3. Uptake Analyzer System Prompt ==========
UPTAKE_SYSTEM_PROMPT = """
You are an expert in Dynamic Assessment (DA) for L2 writing.
Your job is to analyze the learner's response and decide how mediation should proceed.

You will receive:
- original_sentence
- optimized_sentence
- operation (syntactic focus)
- current_level: one of ["implicit", "semi-implicit", "explicit"]
- last_tutor_turn: the tutor's previous message
- learner_turn: the learner's latest response (can be English, Chinese, or mixed)

You must decide ONE label for uptake:

- "good_progress":
    The learner has moved clearly closer to the target structure,
    OR produced a reasonable syntactic improvement in line with the tutor hint,
    OR explicitly shows understanding of the structure.

- "partial_progress":
    The learner attempted a change or asked a relevant question,
    but the structure is still far from the target,
    OR the attempt is incomplete.

- "no_progress":
    The learner repeated the same structure,
    or said they don't know / are confused,
    or responded in a way unrelated to the tutor hint.

Then you must decide how mediation should change:

- If current_level == "implicit":
    - good_progress → "stay_implicit"
    - partial_progress → "stay_implicit"
    - no_progress → "upgrade_to_semi"

- If current_level == "semi-implicit":
    - good_progress → "reset_to_implicit"
    - partial_progress → "stay_semi"
    - no_progress → "upgrade_to_explicit"

- If current_level == "explicit":
    - good_progress → "reset_to_implicit"
    - partial_progress → "reset_to_implicit"
    - no_progress → "stay_explicit"

Return a STRICT JSON object with fields:
{
  "uptake": "good_progress" | "partial_progress" | "no_progress",
  "decision": "stay_implicit" | "stay_semi" | "stay_explicit" |
              "upgrade_to_semi" | "upgrade_to_explicit" |
              "reset_to_implicit"
}
Do not include any other text.
"""


# ========== 4. Syntactic Operation Classifier Prompt ==========
OPERATION_SYSTEM_PROMPT = """
You are a syntactic analyst helping an L2 writing tutor.
You will see an original sentence and its optimized version.

Your task:
1. Compare the two sentences.
2. Decide which MAIN syntactic operation best characterizes the change:

- "subordination": adding a subordinate clause with conjunctions like because, when, although, if, etc.
- "embedding": putting a clause inside a noun phrase (e.g., "the idea that...", relative clauses).
- "non-finite clause": adding to-infinitive, -ing, or -ed clauses to combine actions.
- "nominalization": turning verbs/adjectives/clauses into nouns to make the sentence denser.
- "noun-phrase expansion": adding modifiers or relative clauses to elaborate a noun phrase.
- "prepositional expansion": adding prepositional phrases (in this process, as a result, in academic settings, etc.).
- "general": the change does not clearly fit the above or mixes several.

Return a STRICT JSON object:
{ "operation": "subordination" | "embedding" | "non-finite clause" |
              "nominalization" | "noun-phrase expansion" |
              "prepositional expansion" | "general" }
"""


# ========== 5. MEDIATION_MAP: 六大 operation × 三层 DA 目标说明 ==========
MEDIATION_MAP = {
    "subordination": {
        "implicit":
            "Help the learner notice that there are two related ideas that might want to live together more smoothly, without naming conjunctions or clauses.",
        "semi-implicit":
            "Gently suggest using a linking word that shows cause, time, or contrast (e.g., something like 'because', 'when', or 'although'), but without formally naming the structure.",
        "explicit":
            "Explain that this is subordination, where a subordinate clause expresses relationships such as cause, time, condition, or concession. Briefly illustrate using the optimized sentence."
    },

    "embedding": {
        "implicit":
            "Help the learner sense that one idea could be tucked inside another, rather than stated separately.",
        "semi-implicit":
            "Hint that academic writers sometimes place an idea inside a noun phrase, as in structures like 'the idea that…', but keep the language intuitive.",
        "explicit":
            "Explain embedding explicitly as putting a clause inside a noun phrase (e.g., through 'that'-clauses or relative clauses). Use the optimized sentence as a model."
    },

    "non-finite clause": {
        "implicit":
            "Help the learner feel that actions or events may flow more smoothly without repeating the subject each time.",
        "semi-implicit":
            "Suggest trying a to-phrase or an -ing construction to combine actions gently, without naming grammatical terminology heavily.",
        "explicit":
            "Explain that this is a non-finite clause (to-, -ing, or -ed forms) used to condense actions smoothly. Briefly show how the optimized sentence uses it."
    },

    "nominalization": {
        "implicit":
            "Help the learner sense that the current expression might be made more compact or academic without naming nominalization.",
        "semi-implicit":
            "Hint that turning an action into a noun can make the sentence tighter or more formal, but keep wording light and non-technical.",
        "explicit":
            "Explain nominalization explicitly as converting verbs or adjectives into nouns to create denser academic style, using the optimized sentence as illustration."
    },

    "noun-phrase expansion": {
        "implicit":
            "Help the learner notice that a noun or idea in the sentence might invite a bit more description or detail, without naming modifiers.",
        "semi-implicit":
            "Suggest that writers sometimes add small descriptive elements (like an adjective, prepositional phrase, or a short relative clause) to clarify or enrich a noun phrase.",
        "explicit":
            "Explain noun-phrase expansion explicitly: adding modifiers before or after a noun (adjectives, appositives, relative clauses). Use the optimized sentence for illustration."
    },

    "prepositional expansion": {
        "implicit":
            "Help the learner sense that the sentence might benefit from a gentle hint of context—for example time, place, or manner—without naming prepositional phrases.",
        "semi-implicit":
            "Suggest adding a contextual phrase like 'in this process', 'during the study', or 'as a result' to show relationships more clearly.",
        "explicit":
            "Explain prepositional expansion explicitly: adding prepositional phrases to indicate time, place, manner, reason, or context. Illustrate this using the optimized sentence."
    },

    "general": {
        "implicit":
            "Offer a gentle noticing cue about clarity, flow, or coherence, without naming any grammatical structure.",
        "semi-implicit":
            "Offer a light structural hint that guides the learner toward a more connected or compact structure.",
        "explicit":
            "Provide a clear structural explanation based on the optimized sentence, naming the key syntactic operation if identifiable."
    }
}


# ========== 6. DeepSeek API 调用封装 ==========
def call_deepseek(messages, model=MODEL_NAME, temperature=0.3):
    headers = {
        "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
        "Content-Type": "application/json"
    }
    data = {
        "model": model,
        "messages": messages,
        "temperature": temperature
    }
    resp = requests.post(DEEPSEEK_API_URL, headers=headers, json=data)
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"].strip()


# ========== 7. Sentence Optimizer（终点生成器） ==========
def get_optimized_sentence(original_sentence: str) -> str:
    messages = [
        {"role": "system", "content": OPTIMIZER_SYSTEM_PROMPT},
        {"role": "user", "content": original_sentence}
    ]
    optimized = call_deepseek(messages, temperature=0.2)
    return optimized


# ========== 8. 句法操作分类 ==========
def classify_operation(original: str, optimized: str) -> str:
    user_msg = f"""
Original sentence:
{original}

Optimized sentence:
{optimized}
"""
    messages = [
        {"role": "system", "content": OPERATION_SYSTEM_PROMPT},
        {"role": "user", "content": user_msg}
    ]
    try:
        raw = call_deepseek(messages, temperature=0.0)
        result = json.loads(raw)
        op = result.get("operation", "general")
    except Exception:
        op = "general"
    if op not in MEDIATION_MAP:
        op = "general"
    return op


# ========== 9. Uptake 分析（由 LLM 决定是否升级） ==========
def analyze_uptake(original, optimized, operation, current_level,
                   last_tutor_turn, learner_turn):
    user_msg = {
        "original_sentence": original,
        "optimized_sentence": optimized,
        "operation": operation,
        "current_level": current_level,
        "last_tutor_turn": last_tutor_turn or "",
        "learner_turn": learner_turn
    }
    messages = [
        {"role": "system", "content": UPTAKE_SYSTEM_PROMPT},
        {"role": "user", "content": json.dumps(user_msg, ensure_ascii=False)}
    ]
    try:
        raw = call_deepseek(messages, temperature=0.0)
        result = json.loads(raw)
        uptake = result.get("uptake", "partial_progress")
        decision = result.get("decision", "stay_implicit")
    except Exception:
        uptake = "partial_progress"
        decision = "stay_implicit"
    return uptake, decision

# ========== 9.5 生成 implicit / semi-implicit 提示 ==========
def generate_other_level_turn(original, optimized, operation, level,
                              last_tutor_turn, learner_turn):

    mediation_goal = MEDIATION_MAP.get(operation, MEDIATION_MAP["general"]).get(level, "")

    if level == "implicit":
        return (
            f"Thanks for your sentence! Try reading it aloud and ask yourself: "
            f"could any parts feel like they could flow a bit more smoothly or be joined more naturally? "
            f"Focus especially on how the ideas connect."
        )

    elif level == "semi-implicit":
        return (
            f"You're moving in a good direction. Now, consider whether you could combine some "
            f"parts of your sentence—for example, by adding a small phrase or connector that shows "
            f"time, cause, or extra detail. Think about how the optimized version might do this."
        )

    else:
        return (
            f"Let's keep exploring ways to make your sentence structurally richer, "
            f"while keeping your original meaning."
        )

# ========== 10. 生成 tutor 提示 ==========
def generate_tutor_turn(original, optimized, operation, level,
                        last_tutor_turn, learner_turn):
    # 从 MEDIATION_MAP 获取对应的目标说明
    mediation_goal = MEDIATION_MAP.get(operation, MEDIATION_MAP["general"]).get(level, "")
    
    # 这里将 explicit 逻辑结合到生成提示中
    if level == "explicit":
        # 生成简单的定义
        if operation == "subordination":
            definition = "Subordination involves linking ideas with a dependent clause, like using conjunctions (because, although, etc.)."
        elif operation == "embedding":
            definition = "Embedding is when one clause is placed inside a noun phrase, like 'the idea that...'."
        elif operation == "non-finite clause":
            definition = "Non-finite clauses allow actions to be combined using infinitive verbs or -ing verbs."
        elif operation == "nominalization":
            definition = "Nominalization turns verbs or adjectives into nouns to create more compact and formal expressions."
        elif operation == "noun-phrase expansion":
            definition = "Noun-phrase expansion adds modifiers or relative clauses to elaborate on a noun."
        elif operation == "prepositional expansion":
            definition = "Prepositional expansion involves adding phrases like 'in the process', 'for example', etc., to give more detail."
        else:
            definition = "This structure organizes ideas to increase clarity and academic precision."

        # 微分析（学生句子与优化句子的比较分析）
        analysis = f"Your original sentence, '{original}', can be improved by making it more complex using {operation}. For example, the optimized sentence '{optimized}' shows how the structure works in this context."

        # 示例句（基于优化句子）
        example = f"For example, you could say: '{optimized}'"

        # 返回合成的 tutor 提示
        tutor_turn = f"""
        **Definition:** {definition}

        **Analysis:** {analysis}

        **Example:** {example}

        Try making a similar change in your sentence!
        """
    else:
        # 如果是 implicit 或 semi-implicit，使用之前的简单结构
        tutor_turn = generate_other_level_turn(original, optimized, operation, level, last_tutor_turn, learner_turn)

    return tutor_turn

# ========== 11. Streamlit UI（SCAT 界面） ==========
def init_session_state():
    if "level" not in st.session_state:
        st.session_state.level = "implicit"
    if "original_sentence" not in st.session_state:
        st.session_state.original_sentence = ""
    if "optimized_sentence" not in st.session_state:
        st.session_state.optimized_sentence = ""
    if "operation" not in st.session_state:
        st.session_state.operation = "general"
    if "last_tutor_turn" not in st.session_state:
        st.session_state.last_tutor_turn = ""
    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []  # list of (speaker, text)
    if "last_uptake" not in st.session_state:
        st.session_state.last_uptake = None
    if "last_decision" not in st.session_state:
        st.session_state.last_decision = None


def reset_cycle():
    st.session_state.level = "implicit"
    st.session_state.original_sentence = ""
    st.session_state.optimized_sentence = ""
    st.session_state.operation = "general"
    st.session_state.last_tutor_turn = ""
    st.session_state.chat_history = []
    st.session_state.last_uptake = None
    st.session_state.last_decision = None


def main():

    st.set_page_config(
        page_title="SCAT - Syntax Complexity AI Tutor",
        page_icon="SCAT-3D.png",  # 图标路径
        layout="centered"  # 保留你原来的布局设置
    )

    init_session_state()

       # 标题
    st.markdown(
    f"""
    <div style='text-align:center;'>
        <img src='SCAT-3D.png' width='120'>
    </div>
    <h1 style='text-align:center; font-size:40px; margin-top: 10px;'>
        Syntax Complexity AI Tutor (SCAT)
    </h1>
    <h3 style='text-align:center; color:#AAAAAA;'>
        Dynamic Assessment × Controlled Complexification
    </h3>
    """,
    unsafe_allow_html=True
)


    # 简要说明（用户视角）
    st.markdown(
        """
        ### ✏️ What can SCAT help you with?

        SCAT helps you express the **same ideas** using clearer, smoother, and more academic sentence structures — without changing your meaning.

        When you type a sentence, SCAT will:
        - notice potential areas for syntactic improvement
        - guide you step by step toward stronger structures
        - gently increase complexity only when you're ready
        - support your learning through warm, graduated prompts

        No judgment, no pressure — only small nudges toward richer syntax. ❤️
        """
    )

    st.markdown("---")


    # ===== Step 1: 提交初始句子，开启一个 DA cycle =====
    st.subheader("Step 1 · Start a new sentence cycle")

    col1, col2 = st.columns([3, 1])
    with col1:
        initial_sentence = st.text_area(
            "Your sentence (English / 中文 / mixed is okay):",
            value="",
            height=120
        )
    with col2:
        if st.button("🌱 Start / Reset SCAT cycle"):
            if initial_sentence.strip():
                reset_cycle()
                st.session_state.original_sentence = initial_sentence.strip()

                with st.spinner("Thinking about a more complex but meaning-preserving version..."):
                    optimized = get_optimized_sentence(initial_sentence.strip())
                    st.session_state.optimized_sentence = optimized
                    op = classify_operation(initial_sentence.strip(), optimized)
                    st.session_state.operation = op

                    # 首次 implicit 提示（learner_turn为空，因为是第一轮）
                    tutor_turn = generate_tutor_turn(
                        original=initial_sentence.strip(),
                        optimized=optimized,
                        operation=op,
                        level="implicit",
                        last_tutor_turn="",
                        learner_turn=""
                    )
                    st.session_state.level = "implicit"
                    st.session_state.last_tutor_turn = tutor_turn
                    st.session_state.chat_history.append(("Student (original)", initial_sentence.strip()))
                    st.session_state.chat_history.append(("SCAT", tutor_turn))

            else:
                st.warning("Please enter a sentence before starting a cycle.")

    # ===== 显示对话历史 =====
# ===== 显示对话历史 =====
if st.session_state.chat_history:
    st.markdown("### 💬 Conversation with SCAT")
    for speaker, text in st.session_state.chat_history:

        # ---- SCAT 头像 + 文本 ----
        if speaker.startswith("SCAT"):
            st.markdown(
                f"""
                <div style='display:flex; align-items:flex-start; margin-bottom: 10px;'>
                    <img src='static/SCAT-3D.png' width='32' style='margin-right:10px; margin-top:4px;'>
                    <div style='line-height:1.4;'>
                        <strong>SCAT:</strong> {text}
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )

        # ---- 学生回合 ----
        else:
            st.markdown(
                f"""
                <div style='display:flex; align-items:flex-start; margin-bottom: 10px;'>
                    <div style='font-size:28px; margin-right:8px;'>🙂</div>
                    <div style='line-height:1.4;'>
                        <strong>{speaker}:</strong> {text}
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )

    st.markdown("---")

    # ===== Step 2: 学生回应，系统自动分析 uptake 并升级 =====
    if st.session_state.original_sentence:
        st.subheader("Step 2 · Reply to SCAT and see how the guidance grows")

        learner_response = st.text_area(
            "Type your revision, question, or reaction to SCAT here:",
            height=120,
            key="learner_response_box"
        )

        if st.button("🚀 Send to SCAT"):
            if learner_response.strip():
                # 记录学生回合
                st.session_state.chat_history.append(("Student", learner_response.strip()))

                # Uptake 分析
                with st.spinner("SCAT is reading your response and deciding the next hint..."):
                    uptake, decision = analyze_uptake(
                        original=st.session_state.original_sentence,
                        optimized=st.session_state.optimized_sentence,
                        operation=st.session_state.operation,
                        current_level=st.session_state.level,
                        last_tutor_turn=st.session_state.last_tutor_turn,
                        learner_turn=learner_response.strip()
                    )
                    st.session_state.last_uptake = uptake
                    st.session_state.last_decision = decision

                    # 根据 decision 更新 level / 是否 reset
                    current_level = st.session_state.level

                    if decision == "upgrade_to_semi":
                        new_level = "semi-implicit"
                    elif decision == "upgrade_to_explicit":
                        new_level = "explicit"
                    elif decision == "reset_to_implicit":
                        # 进入新的 implicit cycle，以当前学生句子作为新 original
                        st.session_state.original_sentence = learner_response.strip()
                        with st.spinner("SCAT is building a new target version for your new sentence..."):
                            optimized = get_optimized_sentence(learner_response.strip())
                            st.session_state.optimized_sentence = optimized
                            op = classify_operation(learner_response.strip(), optimized)
                            st.session_state.operation = op
                        new_level = "implicit"
                    elif decision == "stay_semi":
                        new_level = "semi-implicit"
                    elif decision == "stay_explicit":
                        new_level = "explicit"
                    else:  # "stay_implicit" or fallback
                        new_level = "implicit"

                    st.session_state.level = new_level

                    # 生成新的 tutor 提示
                    tutor_turn = generate_tutor_turn(
                        original=st.session_state.original_sentence,
                        optimized=st.session_state.optimized_sentence,
                        operation=st.session_state.operation,
                        level=new_level,
                        last_tutor_turn=st.session_state.last_tutor_turn,
                        learner_turn=learner_response.strip()
                    )
                    st.session_state.last_tutor_turn = tutor_turn
                    st.session_state.chat_history.append(("SCAT", tutor_turn))

            else:
                st.warning("Tell SCAT something first — a revision, a question, or even 'I don't know' is okay.")

    # ===== Teacher / Researcher view =====
    with st.expander("👩‍🏫 Teacher view (for you as researcher / teacher)", expanded=False):
        st.markdown(f"- **Current operation:** `{st.session_state.operation}`")
        st.markdown(f"- **Current internal level:** `{st.session_state.level}`")
        if st.session_state.last_uptake:
            st.markdown(f"- **Last uptake judgement:** `{st.session_state.last_uptake}`")
        if st.session_state.last_decision:
            st.markdown(f"- **Last decision:** `{st.session_state.last_decision}`")
        if st.session_state.original_sentence:
            st.markdown("**Current original sentence for this cycle:**")
            st.write(st.session_state.original_sentence)
        if st.session_state.optimized_sentence:
            st.markdown("**Optimized target sentence (from your Sentence Optimizer):**")
            st.write(st.session_state.optimized_sentence)


if __name__ == "__main__":
    main()
